### PR TITLE
Translation fix

### PR DESCRIPTION
**Pull request by lehaxe**
## Issue being fixed or feature implemented
Just translation fix

## How Has This Been Tested?
Visually

## Breaking Changes
No

## Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by podkovyrin** [comment]
@lehaxe thank you for your contribution! We use Transifex to manage translations and strings-files are pulled automatically from there. I will update our Transifex translation with your changes if you don't mind.

**Comment by podkovyrin** [comment]
Our translations are community-powered and if you'd like to help us translating the wallet I can add you to the translators' team on Transifex.

**Comment by lehaxe** [comment]
> Our translations are community-powered and if you'd like to help us translating the wallet I can add you to the translators' team on Transifex.

No need that, I just doing fix, not more, just interesting.

**Comment by podkovyrin** [comment]
All suggested changes were transferred to our translation service Transifex. Thanks again, @lehaxe!

**Pull request closed without merging**
